<?php

/**
 * @file
 * DNA pair generator module.
 */

function dna_menu() {
  $items['dna_input'] = array(
    'title' => 'DNA Chain Input',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('dna_form'),
    'access callback' => TRUE,
    'type' => MENU_NORMAL_ITEM,
  );
  $items['dna_success'] = array(
    'title' => 'This is the DNA pair',
    'page callback' => 'dna_display',
    'access callback' => TRUE,
    'type' => MENU_CALLBACK,
  );
  return $items;
}

function dna_form() {
  $form['input_dna_chain'] = array(
      '#title' => 'Input DNA chain',
      '#type' => 'textfield',
      '#description' => t("Input the letters A, C, G, and T to find corresponding pair, no spaces please."),
      '#element_validate' => array('element_validate_base')
  );

  $form['submit'] = array(
    '#type' => 'submit',
    '#value' => 'Find Pairs',
  );
  return $form;
}

function element_validate_base($element) {
  $split = str_split($element['#value']); //
  $valid = array('A', 'a', 'C', 'c', 'G', 'g', 'T', 't');
  foreach ($split as $letter) {
    if (!in_array($letter, $valid)) {
      form_error($element, t('Only A, C, G, or T are valid entry.'));
    }
  }
}

function dna_form_submit($form, &$form_state) {
  $input_dna_chain = $form_state['values']['input_dna_chain'];
  $result = dna_finder($input_dna_chain);
  $_SESSION['dna_results'] = $result;
  $form_state['redirect'] = 'dna_success';
}

function dna_finder($dna_chain) {
  $output = "";
  $str = strtolower($dna_chain);

  if ($str === 'a') {
    $output .= 't';
  }

  $output = $dna_chain . ' ' . $output;
  $dna_output = strtoupper($output);
  return $dna_output;
}

function dna_display() {
  $final_output = $_SESSION['dna_results'];
  return "<h2>" . $final_output . "</h2>";
}
