<?php

function dna_menu() {
  $items['dna_input'] = array(
    'title' => 'DNA Chain Input',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('dna_form'),
    'access callback' => TRUE,
    'type' => MENU_NORMAL_ITEM,
  );
  $items['dna_success'] = array(
    'title' => 'This is the DNA pair',
    'page callback' => 'dna_display',
    'access callback' => TRUE,
    'type' => MENU_CALLBACK,
  );
  return $items;
}

function dna_form() {
    $form['input_dna_chain'] = array(
        '#title' => 'Input DNA chain',
        '#type' => 'textfield',
        '#description' => t("Input the letters A, C, G, and T to find corresponding pair"),
        '#element_validate' => array('element_validate_base')
    );

    $form['submit'] = array(
        '#type' => 'submit',
        '#value' => 'Find Pairs',
    );

    return $form;
}

function element_validate_base($element) {
    $split = str_split($element['#value']); //
    $valid = array('A', 'a', 'C', 'c', 'G', 'g', 'T', 't');
    foreach ($split as $base) {
        if (!in_array($base, $valid)) {
            form_error($element, t('Only A, C, G, or T are valid entry.'));
        }
    }
}
